version: '3'

services:
  database:
    image: postgres:13-alpine
    container_name: caronaamiga_db
    env_file: 
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    restart: unless-stopped
