version: '3.7'

services:
  api:
    image: matheusinit/server:1.1
    container_name: caronaamiga_server
    env_file:
      - ./.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:13-alpine
    container_name: caronaamiga_db
    env_file: 
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      timeout: 40s
      interval: 2s
      retries: 20
