name: 'Deploy Backend'

env:
  AZURE_WEBAPP_NAME: carona-amiga-api # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './backend/' 

on:
  push:
    branches: [main]
    paths: 
      - './backend/**'
      - '.github/workflows/backendBuild.yml'
      - '!docs/**'
      
jobs: 
  CI: 
    runs-on: ubuntu-latest
    
    steps:
  
      - uses: actions/checkout@v2.6.0
      
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./backend/.
          push: true
          tags: matheusinit/server
            
      - name: Deploy web App using GH Action azure/webapps-deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
