name: 'Deploy Backend'

on:
  push:
    branches: [FelipeSousaRocha-patch-1]
    paths: 
      - './backend/**'
      - '.github/workflows/backendBuild.yml'
      - '!docs/**'
      
jobs: 
  CI: 
    runs-on: ubuntu-latest
    
    steps:
  
      - uses: actions/checkout@v2.6.0
      
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./backend/.
          push: true
          tags: matheusinit/server
            
      - name: Deploy Docker images
        uses: Azure/pipelines@releases/v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/ricardojackson/PDS'
          azure-pipeline-name: 'PDS' 
          azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
