name: CI

on:
  push:
    branches: [testBuild]
jobs: 
  CI: 
    runs-on: ubuntu-latest
    
    steps:
  
      - uses: actions/checkout@v2.6.0
      
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username:
          password: 
