name: CI

on:
  push:
    branches: [testBuild]
jobs: 
  CI: 
    runs-on: ubuntu-latest
    
    steps:
  
      - uses: actions/checkout@v2.6.0
      
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: .
          push: true
          tags: |
            matheusinit/build:v1
            matheusinit/build:latest
